name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        node-version: ["lts/-1", "lts/*"]
        os: ["ubuntu-latest", "windows-latest"]
        command:
          - name: build
            run: pnpm build
          - name: format-and-lint
            run: pnpm check
          - name: typecheck
            run: pnpm typecheck
          - name: test
            run: pnpm test
          - name: knip
            run: pnpm knip
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.command.name }} - Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: ${{ matrix.command.name }}
        run: ${{ matrix.command.run }}
